# Generated by Django 6.0.6 on 2026-09-28 00:10

import django.core.validators
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


def preserve_subtotals(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.using(schema_editor.connection.alias).update(subtotal=models.F('total'))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.RunPython(preserve_subtotals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z0-9-]{3,30}\\Z', 'Use 3–30 letters, digits, or hyphens.')])),
                ('percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('scope', models.CharField(choices=[('ORDER', 'Whole order'), ('PRODUCTS', 'Selected products')], default='ORDER', max_length=8)),
                ('end_date', models.DateField(help_text='Valid through this date in America/Chicago (Central time).')),
                ('is_active', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('code'), name='coupon_code_case_unique'), models.CheckConstraint(condition=models.Q(('percentage__gte', 1), ('percentage__lte', 100)), name='coupon_percentage_range'), models.CheckConstraint(condition=models.Q(('scope__in', ['ORDER', 'PRODUCTS'])), name='coupon_valid_scope')],
            },
        ),
    ]
