# Generated by Django 6.0.6 on 2026-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_catalog',
            field=models.FileField(blank=True, editable=False, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_detail',
            field=models.FileField(blank=True, editable=False, upload_to='products/'),
        ),
    ]
