# Generated by Django 6.0.6 on 2026-10-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_catalog_product_image_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_catalog',
            field=models.ImageField(blank=True, editable=False, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_detail',
            field=models.ImageField(blank=True, editable=False, upload_to='products/'),
        ),
    ]
